### PR TITLE
Fix package lint issues

### PR DESCRIPTION
**Pull request by wyuenho**
This PR fixes all the issues package-lint complains about.

### CODE REVIEW

**Comment by creichert** [comment]
If you have time to rebase this to get passing checks that would be great. I'll merge it. Thanks!

**Comment by creichert** [comment]
Thanks! Merging on successful checks

**Comment by wyuenho** [comment]
The builds seem to be stuck, can you cancel them and retry?

**Comment by creichert** [comment]
@wyuenho Here's the error I'm seeing: 

```
0.79s$ cask exec ert-runner
../../../.cask/package-build-legacy.el: `object-class-fast' is an obsolete alias (as of 24.4); use `eieio--object-class' instead.
../../../.cask/package-build-legacy.el: `object-class-fast' is an obsolete alias (as of 24.4); use `eieio--object-class' instead.
Symbol's function definition is void: ido-vertical-make-decorations
The command "cask exec ert-runner" exited with 255.
```

**Comment by wyuenho** [comment]
Can you give them a kick now?

**Review by creichert — APPROVED** [review]

**Pull request merged**
